workflows:
  ios-workflow:
    name: iOS Build & Publish
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: ZoneLepro

    environment:
      java: 17
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.betoflys.app"
        XCODE_PROJECT: "iosApp.xcodeproj"
        XCODE_SCHEME: "iosApp"
        APP_ID: 6753973822

    scripts:
      - name: Set up keychain
        script: |
          keychain initialize

      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create

      - name: Add certificates
        script: |
          keychain add-certificates

      - name: Set up code signing
        script: |
          cd $CM_BUILD_DIR/iosApp
          xcode-project use-profiles

      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR/iosApp
          echo "Fetching latest build number from TestFlight..."
          BUILD_NUMBER=$(($(app-store-connect get-latest-testflight-build-number "$APP_ID") + 1))
          echo "✅ New build number: $BUILD_NUMBER"

          # Обновляем CFBundleVersion
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "Info.plist"
          
          # Опционально увеличим и CFBundleShortVersionString при каждом мажорном релизе
          CURRENT_VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "Info.plist")
          echo "Current short version: $CURRENT_VERSION"
          
          /usr/libexec/PlistBuddy -c "Print CFBundleVersion" "Info.plist"

      - name: Build KMP shared framework
        script: |
          export CONFIGURATION="Release"
          export PLATFORM_NAME="iphoneos"
          export SDK_NAME="iphoneos"
          export ARCHS="arm64"
          export VALID_ARCHS="arm64"
          export TARGET_BUILD_DIR="$CM_BUILD_DIR/iosApp/build/Release-iphoneos"
          export FRAMEWORKS_FOLDER_PATH="$TARGET_BUILD_DIR/ComposeApp.framework"
          export BUILT_PRODUCTS_DIR="$TARGET_BUILD_DIR"

          mkdir -p "$TARGET_BUILD_DIR"
          
          ./gradlew :composeApp:embedAndSignAppleFrameworkForXcode -x syncComposeResourcesForIos

      - name: Build iOS .ipa
        script: |
          cd $CM_BUILD_DIR/iosApp
          echo "Building iOS project..."
          xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"

      - name: Debug Info.plist values
        script: |
          echo "Verifying Info.plist values:"
          /usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" iosApp/Info.plist || true
          /usr/libexec/PlistBuddy -c "Print CFBundleVersion" iosApp/Info.plist || true

    artifacts:
      - iosApp/build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: true

